# 작업형1 모의문제1
- data : members.csv
- 한 개의 셀만 사용해서 문제를 풀어주세요

## 문제1
- f1컬럼의 결측치는 중앙 값으로 대체하고
- 나머지 결측치가 있는 데이터(행)을 모두 제거하고,
- 앞에서부터 70% 데이터 중 views 컬럼의 3사분위 수에서 1사분위 수를 뺀 값을 구하시오
- (단, 데이터 70% 지점은 정수형(int) 변환)

In [21]:
# your code
import pandas as pd
import numpy as np
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p1/members.csv")

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          100 non-null    object
 1   age         100 non-null    float64
 2   city        100 non-null    object
 3   f1          69 non-null     float64
 4   f2          100 non-null    int64
 5   f3          72 non-null     object
 6   f4          100 non-null    object
 7   f5          100 non-null    float64
 8   subscribed  100 non-null    object
 9   views       96 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 7.9+ KB

In [24]:
df['f1']=df['f1'].fillna(df['f1'].median())

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          100 non-null    object
 1   age         100 non-null    float64
 2   city        100 non-null    object
 3   f1          100 non-null    float64
 4   f2          100 non-null    int64
 5   f3          72 non-null     object
 6   f4          100 non-null    object
 7   f5          100 non-null    float64
 8   subscribed  100 non-null    object
 9   views       96 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 7.9+ KB

In [26]:
df=df.dropna(axis=0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72 entries, 0 to 99
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          72 non-null     object
 1   age         72 non-null     float64
 2   city        72 non-null     object
 3   f1          72 non-null     float64
 4   f2          72 non-null     int64
 5   f3          72 non-null     object
 6   f4          72 non-null     object
 7   f5          72 non-null     float64
 8   subscribed  72 non-null     object
 9   views       72 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 6.2+ KB

In [32]:
Index_value=int(len(df['views'])*0.7)
df_views_70=df.loc[:Index_value,'views']
df_views_70.describe()

count       38.000000
mean      7739.026316
std       3795.626989
min       3084.000000
25%       5657.250000
50%       7066.000000
75%       9319.250000
max      21550.000000
Name: views, dtype: float64

In [35]:
print(df_views_70.quantile(0.75)-df_views_70.quantile(.25))
print(df_views_70.describe().loc['75%'])

3662.0
9319.25

## 문제2
(변경 후) 변경 전과 동일한 문제입니다. 좀 더 명확하게 수정하였음
- 주어진 데이터에서 결측치가 30% 이상인 컬럼을 A, 결측치가 30% 미만, 20% 이상인 컬럼을 B라고 가정하자.
- A에 해당하는 컬럼은 결측치가 있는 데이터(행)를 삭제하시오.
- B에 해당하는 컬럼은 결측치를 최빈값으로 대체하시오.
- 'f3'컬럼의 'gold' 값을 가진 데이터 수를 구하시오


(변경 전)
- 주어진 데이터에서 결측치가 30%이상 되는 컬럼을 찾고 해당 컬럼에 결측치가 있는 데이터(행)를 삭제 함.
- 그리고 30% 미만, 20% 이상인 결측치가 있는 컬럼은 최빈값으로 값을 대체하고
- 'f3'컬럼의 'gold' 값을 가진 데이터 수를 출력하세요!

In [45]:
# your code
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p1/members.csv")
df.isnull().sum()

id             0
age            0
city           0
f1            31
f2             0
f3            28
f4             0
f5             0
subscribed     0
views          4
dtype: int64

In [78]:
import numpy as np
cond=df['f1'].isna()
temp=df[~cond]
temp['f3']=temp['f3'].fillna(temp['f3'].mode()[0])
gold_table=temp['f3']=='gold'
print(sum(gold_table))

56

## 문제3
- views 컬럼에 결측치가 있는 데이터(행)을 삭제하고,
- f3 컬럼의 결측치는 0, silver는 1, gold는 2, vip는 3 으로 변환한 후 총 합을 정수형으로 출력하시오

# 풀이

In [105]:
import pandas as pd
import numpy as np
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p1/members.csv")

df=df.dropna(subset=['views'])

def Medal_to_points(Medal):
  if Medal=='vip':
    points=3
  elif Medal=='gold':
    points=2
  elif Medal=='silver':
    points=1
  else:
    points=0

  return points


# df['f3']=df['f3'].replace([np.nan,'gold','silver','vip'],[0,2,1,3])
df['f3']=df['f3'].apply(Medal_to_points)
Total_value=df['f3'].sum()
print(Total_value)

133

## 문제1
- f1컬럼의 결측치는 중앙 값으로 대체하고
- 나머지 결측치가 있는 데이터(행)을 모두 제거하고,
- 앞에서부터 70% 데이터 중 views 컬럼의 3사분위 수에서 1사분위 수를 뺀 값을 구하시오
- (단, 데이터 70% 지점은 정수형(int) 변환)

In [ ]:
# 풀이
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p1/members.csv")
# df = pd.read_csv("members.csv")

df['f1'] = df['f1'].fillna(df['f1'].median())
# print(df.isnull().sum())

# print(df.shape)
df = df.dropna()
# print(df.shape)

df = df[:int(len(df) * 0.7)]

r1 = df['views'].quantile(.75)
r2 = df['views'].quantile(.25)

print(r1 - r2)

3261.0

## 문제2
(변경 후) 변경 전과 동일한 문제입니다. 좀 더 명확하게 수정하였음
- 주어진 데이터에서 결측치가 30% 이상인 컬럼을 A, 결측치가 30% 미만, 20% 이상인 컬럼을 B라고 가정하자.
- A에 해당하는 컬럼은 결측치가 있는 데이터(행)를 삭제하시오.
- B에 해당하는 컬럼은 결측치를 최빈값으로 대체하시오.
- 'f3'컬럼의 'gold' 값을 가진 데이터 수를 구하시오


(변경 전)
- 주어진 데이터에서 결측치가 30%이상 되는 컬럼을 찾고 해당 컬럼에 결측치가 있는 데이터(행)를 삭제 함.
- 그리고 30% 미만, 20% 이상인 결측치가 있는 컬럼은 최빈값으로 값을 대체하고
- 'f3'컬럼의 'gold' 값을 가진 데이터 수를 출력하세요!

In [76]:
# 풀이
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p1/members.csv")
# df = pd.read_csv("members.csv")

# print(df.isnull().sum())

# print(len(df) * 0.3)
# f1 삭제
# f3 최빈값

# print(df.shape)
df = df.dropna(subset=['f1'])
# print(df.shape)

# print(df.head())
df['f3'] = df['f3'].fillna(df['f3'].mode()[0])
# print(df.head())

# df.isnull().sum()

print(sum(df['f3'] == 'gold'))

56

## 문제3
- views 컬럼에 결측치가 있는 데이터(행)을 삭제하고,
- f3 컬럼의 결측치는 0, silver는 1, gold는 2, vip는 3 으로 변환한 후 f3 컬럼의 총 합을 정수형으로 출력하시오

In [ ]:
# replace 활용
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p1/members.csv")
# df = pd.read_csv("members.csv")

# print(df.shape)
df = df.dropna(subset=['views'])
# print(df.shape)

# print(df.head(7))
import numpy as np
df['f3'] = df['f3'].replace(np.nan,0).replace('silver',1).replace('gold',2).replace('vip',3)
# df['f3'] = df['f3'].replace('silver',1)
# df['f3'] = df['f3'].replace('gold',2)
# df['f3'] = df['f3'].replace('vip',3)
# print(df.head(7))

print(df['f3'].sum())

133

In [ ]:
# map 활용
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p1/members.csv")
# df = pd.read_csv("members.csv")

df = df.dropna(subset=['views'])

dict_list = {np.nan:0, 'silver':1, 'gold':2, 'vip':3}
df['f3'] = df['f3'].map(dict_list)

print(df['f3'].sum())

133

In [ ]:
# 조건 활용
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p1/members.csv")
# df = pd.read_csv("members.csv")

df = df.dropna(subset=['views'])

r1 = sum(df['f3'] == 'silver') * 1
r2 = sum(df['f3'] == 'gold') * 2
r3 = sum(df['f3'] == 'vip') * 3
print(r1 + r2 + r3)

133